# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07bdfbe881563db3e5db7b58cb33a2ea9abb6af8cdecbc0832c753c2d7056769c7bb42bc548e0d8649881b6e5913446ea2422a47360990551c845ffed772d068

test:
  secret_key_base: 02b3f24aa54a58dc245162e79ff98ba5658629006f27cd9ef76fa5d4260730535d35bc79c54480f14856e5d4ce00aa47e8664afb00f128038d360a8153c169f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
